---
dataset: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Datasets\VOC2012'

Image:
    Size_x : 224
    Size_y : 224
    Size_channel : 3
    
train:
    optimizer: "adam"
    learning_rate: 0.001
    batch_size : 20
    epoch: 300
    use_multiprocessing: True
    weight_initialization: 
        use_pretrained: False
        restore_from: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\last_weight.h5'
    
    Output:
        weight: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\weights.h5'
        
Network:
    train_from_scratch: False
    Decoder: '8X' # Could be 16x,32x
    graph_path: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\graph.json'
    num_classes: 21
    loss: 'categorical_cross_entropy'
    modelpath: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\model.png'
    
Data_Aug:
    use_aug: True
    
Callbacks:
    Earlystop:
        Use_Early_Stop: True
        patience: 10
        monitor: 'val_loss'
        
    Model_Checkpoint_Best:
        enabled: True
        out_file: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\best_weight.h5'
        monitor: 'val_loss'
        
    Model_Checkpoint_last:
        enabled: True
        Out_file: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\Generated\last_weight.h5'
        
    Tensorboard:
        enabled: True
        event_file: 'E:\Study Material\Python_Machine_AI\Deep Learning_Lessons\Praktisch\Tensorflow\Projects\Semantic Segmentation FCN\TensorBoard\'
        
    OneCycle:
        enabled: True
        max_rate: 0.05
        
    
        
    
